/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarouselBox: typeof import('./src/components/CarouselBox.vue')['default']
    CarouselWrap: typeof import('./src/components/CarouselWrap.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOpiton: typeof import('element-plus/es')['ElOpiton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpGoodsFilled: typeof import('~icons/ep/goods-filled')['default']
    IEpMoneyBagBold: typeof import('~icons/ep/money-bag-bold')['default']
    IEpMoneyBagBoldFilled: typeof import('~icons/ep/money-bag-bold-filled')['default']
    IEpPrinter: typeof import('~icons/ep/printer')['default']
    IEpPrinterFilled: typeof import('~icons/ep/printer-filled')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    IEpService: typeof import('~icons/ep/service')['default']
    IEpServiceFilled: typeof import('~icons/ep/service-filled')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    IEpWalletFilled: typeof import('~icons/ep/wallet-filled')['default']
    IndexFiexed: typeof import('./src/components/indexFiexed.vue')['default']
    IndexFixed: typeof import('./src/components/IndexFixed.vue')['default']
    PublicFooter: typeof import('./src/components/PublicFooter.vue')['default']
    PublicHeader: typeof import('./src/components/PublicHeader.vue')['default']
    PublicMenuList: typeof import('./src/components/PublicMenuList.vue')['default']
    PublicTool: typeof import('./src/components/PublicTool.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
